#Types
NORMAL="Normal"
FIRE="Fire"
WATER="Water"
GRASS="Grass"
ELECTRIC="Electric"
ICE="Ice"
FIGHTING="Fighting"
POISON="Poison"
GROUND="Ground"
FLYING="Flying"
PSYCHIC="Psychic"
HUG="Bug"
ROCK="Rock"
GHOST="Ghost"
DARK="Dark"
DRAGON="Dragon"
STEEL="Steel"
FAIRY="Fairy"

#Move types
PHYSICAL_MOVE="Pyshical"
SPECIAL_MOVE="Special"
STATUS_MOVE="Status"

#Pokemon stats
NAME="Name"
TYPE1="Type1"
TYPE2="Type2"
HP="Hp"
ATTACK="Attack"
DEFENSE="Defense"
SPATTACK="Spattack"
SPDEFENSE="Spdefense"
SPEED="Speed"